Social media test - IFTAQCAA-10
Nikodych/ifa-134.ta pull request #40
Opened 2021-12-01 13:32 UTC by Ferrl-m

2021-12-01 21:21 UTC, Nikodych requested changes

2021-12-01 21:21 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/HomePage.java
> +        String expectedUrl = SocialMedia.valueOf(mediaName.toUpperCase()).getSocialMediaLink();
var instead of String

2021-12-01 21:21 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/HomePage.java
> +        Selenide.switchTo().window(1);
create util class and name it something like BrowserTabHelper and move there these lines and create separate methods such as
void switchToTab(int tabNumber){switchTo().window(tabNumber);}
String getCurrentUrl(){return url();}
void closeTab(){closeWindow();}


and in a place where you will need these methods, you will need to call it through a variable or just new BrowserTabHelper().getCurrentUrl();

after closing tab you probably need to switch to first tab

2021-12-01 21:21 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/HomePage.java
> +    public boolean isSocialMediaCorrect(String mediaName) {
based on comments here, this method not needed, most of these should be performed in test

2021-12-01 21:21 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/HomePageTest.java
> +                .as("Social media link shoul correspond " + socialMediaName)
should correspond:

2021-12-03 10:39 UTC, Nikodych requested changes

2021-12-03 10:39 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/models/BrowserTabHelper.java
> +    public void switchToTab(int tabNumber) {
make methods static

2021-12-03 10:39 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/HomePage.java
> +    public boolean isSocialMediaCorrect(String mediaName) {
if this method is no longer used, it could be deleted

2021-12-03 10:39 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/HomePageTest.java
> +        BrowserTabHelper.switchToTab(1);
static import if you make these methods static

2021-12-03 10:39 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/HomePageTest.java
> +        var actualUrl = WebDriverRunner.getWebDriver().getCurrentUrl();
same, and here you should use method from helper class

2021-12-03 10:39 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/HomePageTest.java
> +        BrowserTabHelper.closeTab();
same, and probably move this method under assert, it is needed in case if assert fails and on this tab should make a screenshot

2021-12-03 10:39 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/HomePageTest.java
> +                .as("Social media link shoul correspond " + socialMediaName)
this

2021-12-03 11:15 UTC, Ferrl-m commented on src/main/java/com/softserveinc/ita/models/BrowserTabHelper.java
> +    public void switchToTab(int tabNumber) {
@UtilityClass makes methods static
![image](https://user-images.githubusercontent.com/72382320/144593635-327611d0-1214-47e6-8815-d3500f653d1d.png)

2021-12-03 13:19 UTC, Nikodych requested changes

2021-12-03 13:19 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/HomePage.java
> +
delete empty line

2021-12-03 13:19 UTC, Nikodych commented on src/main/java/com/softserveinc/ita/pageobjects/HomePage.java
> +
delete extra empty line

2021-12-03 13:19 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/HomePageTest.java
> +
delete empty line

2021-12-03 13:19 UTC, Nikodych commented on src/test/java/com/softserveinc/ita/HomePageTest.java
> +        closeTab();
before close method add empty line

2021-12-03 13:51 UTC, Nikodych approved these changes

2021-12-03 13:51 UTC, merged