Created Test Suite - IFTAQCAA-18
Nikodych/ifa-134.ta pull request #42
Opened 2021-12-01 17:15 UTC by Ferrl-m

2021-12-01 21:29 UTC, Nikodych requested changes

2021-12-01 21:29 UTC, Nikodych commented on testng.xml
> +<suite name = "Suite1">
create another one for difference, with a list of test methods

<test name="">
        <classes>
            <class name="">
                <methods>
                    <include name=""/>
                    <include name=""/>
                </methods>
            </class>
        </classes>
    </test>

and add to any of the suites such config

<suite name="" parallel="tests" thread-count="1">

2021-12-01 21:29 UTC, Nikodych commented on README.md
> +How to run Test Suite
also, add instruction on how to run through the console with mvn command

2021-12-02 14:55 UTC, Ferrl-m commented
using mvn clean test -DsuiteXmlFile=fileName.xml makoviichukTests works correctly 
![image](https://user-images.githubusercontent.com/72382320/144445943-8eb792fe-fe5b-454c-ac78-2334cd81f789.png)

but allTests with same tests fails 
![image](https://user-images.githubusercontent.com/72382320/144446090-52e9cab0-0d55-4c42-9587-43ebbcbe2842.png)

2021-12-03 17:30 UTC, Nikodych requested changes

2021-12-03 17:30 UTC, Nikodych commented on allTests.xml
> +<suite name = "All Tests">
so you are able for all tests to use the previous approach, use this approach for such suite as "Smoke suite" and choose few test with this approach

2021-12-03 17:30 UTC, Nikodych commented on pom.xml
> +                <artifactId>maven-surefire-plugin</artifactId>
probably Pavlo also imported this plugin, and it's already merged

2021-12-10 09:31 UTC, Nikodych approved these changes

2021-12-10 09:32 UTC, merged